-- TABLE
CREATE TABLE Notes ( Grade INTEGER, Min_Value Integer, Max_Value INTEGER );
CREATE TABLE Students ( ID INTEGER PRIMARY KEY AUTOINCREMENT, Name STRING, Value INTEGER );
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
